### ISSUE TITLE
USER STORY <TITLE>

### ISSUE THREAD

**Issue by MichaelSturgeon** [MichaelSturgeon/My-First-Agile-Project#5]
As an **Administrator** I can **choose the expiry date of the poll ** so that **it automatically hides**

## Acceptance Criteria
- Acceptance Criteria 1: When publishing the poll, provide a dropdown calendar to select the target expiry date.
- Acceptance Criteria 2: The expiry date should be present to the user
- Acceptance Criteria 3: The poll should only ever be displayed at the top of the home page

## Tasks
- [ ] Task 1: Create date selector calendar
- [ ] Task 2: Create JavaScript function to display the expiry date of poll to the user
- [ ] Task 3: Test functionality
